[#102] mydashboard 페이지 기능 구현
Team-Plants/PLANTS pull request #111
Opened 2023-12-31 22:52 UTC by hyejungan

## 📖 작업 내용
- [x] '로고' 버튼을 클릭하면 `/mydashboard` 페이지로 이동합니다.
- [x] 내가 만든 대시보드끝에는  👑 이 붙습니다
- [x] 내 대시보드는 페이지네이션으로 구현합니다
- [ ] 초대받은 대시보드는 무한스크롤로 구현합니다
- [x] 내 대시보드를 각각을 클릭하면 해당 대시보드 페이지로`/{boardid}/mydashboard` 이동합니다.
- [x] '+' 버튼을 클릭하면 대시보드 생성 모달이 나타납니다.
- [x] 초대받은 대시보드가 없으면 “아직 초대받은 대시보드가 없어요”문구를 보여줍니다.
- [x] 초대받은 대시보드에서 이름(title)로 검색이 가능합니다.
- [x] 초대받은 대시보드에서 '수락' 버튼을 누르면 대시보드가 추가됩니다.
- [x] 초대받은 대시보드에서 '거절' 버튼을 누르면 해당 대시보드는 삭제됩니다.

## ✅ PR 포인트
- 무한스크롤을 어떻게 해야할 지 모르겠어요,,, usehook에서 useRef를 사용하지 않고 useState target으로 사용하는 방법이 이해하기 어려웠어요ㅠ 아시는 분은 좀 알려주세요ㅜㅜ

- css 수정했습니다.
- 
## 📸 스크린샷

https://github.com/Team-Plants/PLANTS/assets/138510303/c65eae73-3d68-4c7f-97ac-69ac36a322b1

2024-01-01 13:25 UTC, K-Y-Hoo requested changes

2024-01-01 13:25 UTC, K-Y-Hoo commented on src/pages/mydashboard/index.tsx
> +import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
고생 많으셨습니다..! 👍👍
혜정님 혹시 useInfiniteQuery로 무한스크롤 기능 구현이 내일까지 힘들 것 같다고 생각되시면 내일 같이 제가 만든 무한스크롤 커스텀 훅을 사용해서 구현해보는거 어떠세요?!

2024-01-01 19:06 UTC, hyejungan commented on src/pages/mydashboard/index.tsx
> +import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
좋아요! 감사합니다!

2024-01-04 04:48 UTC, BeMatthewsong commented on src/pages/mydashboard/index.tsx
> +    placeholderData: dashboard,
오 이게 깜박임을 방지하는 속성인가요?

2024-01-04 04:49 UTC, BeMatthewsong commented on src/api/invitations.ts
> +  const result = await axios.post('/api/withAuthHandler', option);
슬래시가 많이 괴롭히셨군요

2024-01-04 04:51 UTC, hyejungan commented on src/pages/mydashboard/index.tsx
> +    placeholderData: dashboard,
이전값을 가지고 있다가 업로드 하면 그때서야 보이게 해서 깜빡임을 덜하게 보이는 것 같아요!

2024-01-04 04:56 UTC, BeMatthewsong approved these changes
엄청난 걸 하셨네요! 고생많으셨습니다! 👍🏻

2024-01-04 04:56 UTC, BeMatthewsong commented on src/components/button/buttonGroup.tsx
> +      queryClient.invalidateQueries({ queryKey: ['dashboards'] });
쿼리 키를 동시에 두 개를 못 보내나보네요...! 
공식문서 통해서 아셨나요?

2024-01-04 04:56 UTC, BeMatthewsong commented on src/hooks/useDebounce.ts
> +export default useDebounce;
입력 처리 디바운스 좋네요 👍🏻

2024-01-04 06:46 UTC, SoobinJ approved these changes

2024-01-04 06:48 UTC, hanseulhee approved these changes

2024-01-04 06:48 UTC, hanseulhee commented on src/components/modal/newDashboardModal/newDashboardModal.tsx
> +    onSuccess: (data) => {
센스 미쳐따 👍🏻👍🏻👍🏻

2024-01-04 06:49 UTC, K-Y-Hoo approved these changes

2024-01-04 07:06 UTC, merged